services:
  - type: web
    name: arsha-lost-and-found
    env: python
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SESSION_SECRET
        generateValue: true
